[package]
name = "tcw3_calc_meta"
version = "0.1.0"
authors = ["tcpp"]
edition = "2018"

[build-dependencies.tcw3_designer]
git = "https://github.com/yvt/Stella2.git"
rev = "9be823965b2f62955fd48e82f392d4ea07d8808b"

[build-dependencies.tcw3_meta]
git = "https://github.com/yvt/Stella2.git"
rev = "9be823965b2f62955fd48e82f392d4ea07d8808b"

[lib]
path = "lib.rs"
